// Código generado automáticamente. No editar.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "nena-front":return img`
. f f f . f f f f . f f f . 
f f f f f c c c c f f f f f 
f f f f b c c c c b f f f f 
f f f c 3 c c c c 3 c f f f 
. f 3 3 c c c c c c 3 3 f . 
. f c c c c 4 4 c c c c f . 
. f f c c 4 4 4 4 c c f f . 
. f f f b f 4 4 f b f f f . 
. f f 4 1 f d d f 1 4 f f . 
. . f f d d d d d d f f . . 
. . e f e 4 4 4 4 e f e . . 
. e 4 f b 3 3 3 3 b f 4 e . 
. 4 d f 3 3 3 3 3 3 c d 4 . 
. 4 4 f 6 6 6 6 6 6 f 4 4 . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`;
            case "image3":
            case "robot_front":return img`
.....bbbbbbbbb.....
....fffffffffff....
...2222222222222...
..f2fffffffffff2f..
.bf2fff9fff9fff2fb.
.bf2ff989f989ff2fb.
.bf2ff989f989ff2fb.
.bf2ff989f989ff2fb.
.bf2fff9fff9fff2fb.
..f2fffffffffff2f..
...2222222222222...
....fffffffffff....
......bbbbbbb......
.......fffff.......
......fffffff......
.....ddddddddd.....
....d11117111dd....
....1111171111d....
....22111d11122....
....dd22222221d....
....11dddddddd.....
......d11111d......
.......ddddd.......
`;
            case "image5":
            case "robot_right":return img`
...bbbbbbbbb.......
..ffffffffffff.....
.ffffffff22222.....
bffffffff2ffff.....
bffffbbbf2fff9.....
bfffbbdbf2ff98.....
bffbbbdbf2ff98.....
bffbbbdbf2ff98.....
bffbbbdbf2ff98.....
bfffbbdbf2fff9.....
bffffbbbf2ffff.....
.ffffffff22222.....
..ffffffffffff.....
....fffbbbbb.......
....fffff..........
....ffffff.........
...dddddddd........
..dddddddd17.......
..dd1111d117.......
..d222222217.......
..dd11111122.......
..dd111111dd.......
...ddddddddd.......
`;
            case "image4":
            case "robot_left":return img`
.......bbbbbbbbb...
.....ffffffffffff..
.....22222ffffffff.
.....ffff2ffffffffb
.....9fff2fbbbffffb
.....89ff2fbdbbfffb
.....89ff2fbdbbbffb
.....89ff2fbdbbbffb
.....89ff2fbdbbbffb
.....9fff2fbdbbfffb
.....ffff2fbbbffffb
.....22222ffffffff.
.....ffffffffffff..
.......bbbbbfff....
..........fffff....
.........ffffff....
........dddddddd...
.......71dddddddd..
.......711d1111dd..
.......712222222d..
.......22111111dd..
.......dd111111dd..
.......ddddddddd...
`;
            case "image6":
            case "robot_up":return img`
.....bbbbbbbbb.....
....fffffffffff....
...fffffffffffff...
..fffffffffffffff..
.bffbbbbbbbbbbbffb.
.bffbbbbbbbbbbbffb.
.bffbbbbbbbbbbbffb.
.bffbbbbbbbbbbbffb.
.bffbbbbbbbbbbbffb.
..fffffffffffffff..
...fffffffffffff...
....fffffffffff....
......bbbbbbb......
.......fffff.......
......fffffff......
.....ddddddddd.....
....d11117111dd....
....1111171111d....
....22111d11122....
....dd22222221d....
....11dddddddd.....
......d11111d......
.......ddddd.......
`;
            case "image7":
            case "boss_front":return img`
.....bbbbbbbbb.....
....fffffffffff....
...aaaaaaaaaaaaa...
..fafffffffffffaf..
.bfafff5fff5fffafb.
.bfaff525f525ffafb.
.bfaff525f525ffafb.
.bfaff525f525ffafb.
.bfafff5fff5fffafb.
..fafffffffffffaf..
...aaaaaaaaaaaaa...
....fffffffffff....
......bbbbbbb......
.......fffff.......
......fffffff......
.....ddddddddd.....
....d1111a111dd....
....11111a1111d....
....aa111d111aa....
....ddaaaaaaa1d....
....11dddddddd.....
......d11111d......
.......ddddd.......
`;
            case "image8":
            case "boss_right":return img`
...bbbbbbbbb.......
..ffffffffffff.....
.ffffffffaaaaa.....
bffffffffaffff.....
bffffbbbfafff5.....
bfffbbdbfaff54.....
bffbbbdbfaff54.....
bffbbbdbfaff54.....
bffbbbdbfaff54.....
bfffbbdbfafff5.....
bffffbbbfaffff.....
.ffffffffaaaaa.....
..ffffffffffff.....
....fffbbbbb.......
....fffff..........
....ffffff.........
...dddddddd........
..dddddddd1a.......
..dd1111d11a.......
..daaaaaaa1a.......
..dd111111aa.......
..dd111111dd.......
...ddddddddd.......
`;
            case "image9":
            case "boss_left":return img`
.......bbbbbbbbb...
.....ffffffffffff..
.....aaaaaffffffff.
.....ffffaffffffffb
.....5fffafbbbffffb
.....45ffafbdbbfffb
.....45ffafbdbbbffb
.....45ffafbdbbbffb
.....45ffafbdbbbffb
.....5fffafbdbbfffb
.....ffffafbbbffffb
.....aaaaaffffffff.
.....ffffffffffff..
.......bbbbbfff....
..........fffff....
.........ffffff....
........dddddddd...
.......a1dddddddd..
.......a11d1111dd..
.......a1aaaaaaad..
.......aa111111dd..
.......dd111111dd..
.......ddddddddd...
`;
            case "image10":
            case "boss_up":return img`
.....bbbbbbbbb.....
....fffffffffff....
...fffffffffffff...
..fffffffffffffff..
.bffbbbbbbbbbbbffb.
.bffbbbbbbbbbbbffb.
.bffbbbbbbbbbbbffb.
.bffbbbbbbbbbbbffb.
.bffbbbbbbbbbbbffb.
..fffffffffffffff..
...fffffffffffff...
....fffffffffff....
......bbbbbbb......
.......fffff.......
......fffffff......
.....ddddddddd.....
....d1111a111dd....
....11111a1111d....
....aa111d111aa....
....ddaaaaaaa1d....
....11dddddddd.....
......d11111d......
.......ddddd.......
`;
            case "image2":
            case "piece1":return img`
. . f f f f f f f f f f f f . . 
. . f 9 9 9 9 9 9 9 9 9 9 f . . 
. . f 9 f f f f f f f f 9 f . . 
. f 9 9 9 9 9 9 9 9 9 9 9 9 f . 
. f 9 9 f f f f f f f 9 9 9 f . 
. f 9 9 9 9 9 9 9 9 9 9 9 9 f . 
. f 9 9 f f f f 9 f f f 9 9 f . 
. f 9 9 9 9 9 9 9 9 9 9 9 9 f . 
. f 9 9 f f f f f f f f 9 9 f . 
. f 9 9 f 9 9 9 9 9 9 9 9 9 f . 
. f 9 9 9 9 9 9 9 9 9 9 9 9 f . 
. f 9 9 f f f f f f f 9 9 9 f . 
. f 9 9 9 9 9 9 9 9 9 9 9 9 f . 
. . f 9 f f f 9 9 9 9 9 9 f . . 
. . f 9 9 9 9 9 9 9 9 9 9 f . . 
. . f f f f f f f f f f f f . . 
`;
            case "image11":
            case "piece2":return img`
. . f f f f f f f f f f f f . . 
. . f 4 4 4 4 4 4 4 4 4 4 f . . 
. . f 4 f f f f f f f f 4 f . . 
. f 4 4 4 4 4 4 4 4 4 4 4 4 f . 
. f 4 4 f f f f f f f 4 4 4 f . 
. f 4 4 4 4 4 4 4 4 4 4 4 4 f . 
. f 4 4 f f f f 4 f f f 4 4 f . 
. f 4 4 4 4 4 4 4 4 4 4 4 4 f . 
. f 4 4 f f f f f f f f 4 4 f . 
. f 4 4 f 4 4 4 4 4 4 4 4 4 f . 
. f 4 4 4 4 4 4 4 4 4 4 4 4 f . 
. f 4 4 f f f f f f f 4 4 4 f . 
. f 4 4 4 4 4 4 4 4 4 4 4 4 f . 
. . f 4 f f f 4 4 4 4 4 4 f . . 
. . f 4 4 4 4 4 4 4 4 4 4 f . . 
. . f f f f f f f f f f f f . . 
`;
            case "image12":
            case "piece3":return img`
. . f f f f f f f f f f f f . . 
. . f 3 3 3 3 3 3 3 3 3 3 f . . 
. . f 3 f f f f f f f f 3 f . . 
. f 3 3 3 3 3 3 3 3 3 3 3 3 f . 
. f 3 3 f f 3 f f f f 3 3 3 f . 
. f 3 3 3 3 3 3 3 3 3 3 3 3 f . 
. f 3 3 f f f f 3 f f f 3 3 f . 
. f 3 3 3 3 3 3 3 3 3 3 3 3 f . 
. f 3 3 f f f f f f f f 3 3 f . 
. f 3 3 f 3 3 3 3 3 3 3 3 3 f . 
. f 3 3 3 3 3 3 3 3 3 3 3 3 f . 
. f 3 3 f f f f f f f 3 3 3 f . 
. f 3 3 3 3 3 3 3 3 3 3 3 3 f . 
. . f 3 f f f 3 3 3 3 3 3 f . . 
. . f 3 3 3 3 3 3 3 3 3 3 f . . 
. . f f f f f f f f f f f f . . 
`;
            case "image13":
            case "bug_up":return img`
..........f...........f..........
..........ff.........ff..........
...........ff.fffff.ff...........
............ffdaaaaff............
...........fcdaaaaaaaf...........
..........fcdaaaaaaaacf..........
..........fcaaaaaaaaacf..........
..ff......fcaaaaaaaaacf......ff..
...ff.....fcccccccccccf.....ff...
....fff..fffffffffffffff..fff....
.....ffffbbdddbfffbdddbbffff.....
........fbdddddbfbdddddbf........
........fbddddddfddddddbf........
.......ffbddddddfddddddbff.......
.......ffbddddddfddddddbff.......
...ffffffbddddddfddddddbffffff...
..fffffffbddddddfddddddbfffffff..
.ff.....fbddddddfddddddbf.....ff.
.f......fbddddddfddddddbf......f.
........fbbdddddfdddddbbf........
.........fbdddddfdddddbf.........
........ffbbddddfddddbbff........
......fff.fbbdddfdddbbf.fff......
.....ff....fbbbdfddbbf....ff.....
....ff......fbbbfbbbf......ff....
....f........fffffff........f....
....f.......................f....
.................................
`;
            case "image14":
            case "bug_down":return img`
.................................
....f.......................f....
....f........fffffff........f....
....ff......fbbbfbbbf......ff....
.....ff....fbbbdfddbbf....ff.....
......fff.fbbdddfdddbbf.fff......
........ffbbddddfddddbbff........
.........fbdddddfdddddbf.........
........fbbdddddfdddddbbf........
.f......fbddddddfddddddbf......f.
.ff.....fbddddddfddddddbf.....ff.
..fffffffbddddddfddddddbfffffff..
...ffffffbddddddfddddddbffffff...
.......ffbddddddfddddddbff.......
.......ffbddddddfddddddbff.......
........fbddddddfddddddbf........
........fbdddddbfbdddddbf........
.....ffffbbdddbfffbdddbbffff.....
....fff..fffffffffffffff..fff....
...ff.....fcccccccccccf.....ff...
..ff......fcaaaaaaaaacf......ff..
..........fcaaaaaaaaacf..........
..........fcdaaaaaaaacf..........
...........fcdaaaaaaaf...........
............ffdaaaaff............
...........ff.fffff.ff...........
..........ff.........ff..........
..........f...........f..........
`;
            case "image15":
            case "bug_left":return img`
............................
.................ff.........
.......f........ff..........
.......ff......ff...........
........ff.....ff.......fff.
.........ff....ff......ff...
.........ff....ff.....ff....
..........f..ffff.....f.....
..........ffffffffff.ff.....
.........fbbbbbbbbbbff......
ff...fffffbddddddddbbbf.....
.ff.fccccfdddddddddddbbf....
..ffaaaacfddddddddddddbbf...
...faaaacfdddddddddddddbbf..
..faaaaacfbdddddddddddddbf..
..faaaaacffbddddddddddddbf..
..faaaaacfffffffffffffffff..
..faaaaacffbddddddddddddbf..
..fdaaaacfbddddddddddddbbf..
...fdaaacfdddddddddddddbbf..
..ffcdaacfddddddddddddbbf...
.ff.fccccfdddddddddddbbf....
ff...fffffbddddddddbbbf.....
.........fbbbbbbbbbbff......
..........ffffffffff.ff.....
..........f..ffff.....f.....
.........ff....ff.....ff....
.........ff....ff......ff...
........ff.....ff.......fff.
.......ff......ff...........
.......f........ff..........
.................ff.........
............................
`;
            case "image16":
            case "bug_right":return img`
............................
.........ff.................
..........ff........f.......
...........ff......ff.......
.fff.......ff.....ff........
...ff......ff....ff.........
....ff.....ff....ff.........
.....f.....ffff..f..........
.....ff.ffffffffff..........
......ffbbbbbbbbbbf.........
.....fbbbddddddddbfffff...ff
....fbbdddddddddddfccccf.ff.
...fbbddddddddddddfcaaaaff..
..fbbdddddddddddddfcaaaaf...
..fbdddddddddddddbfcaaaaaf..
..fbddddddddddddbffcaaaaaf..
..fffffffffffffffffcaaaaaf..
..fbddddddddddddbffcaaaaaf..
..fbbddddddddddddbfcaaaadf..
..fbbdddddddddddddfcaaadf...
...fbbddddddddddddfcaadcff..
....fbbdddddddddddfccccf.ff.
.....fbbbddddddddbfffff...ff
......ffbbbbbbbbbbf.........
.....ff.ffffffffff..........
.....f.....ffff..f..........
....ff.....ff....ff.........
...ff......ff....ff.........
.fff.......ff.....ff........
...........ff......ff.......
..........ff........f.......
.........ff.................
............................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "nena-animation-down":
            case "anim1":return [img`
. f f f . f f f f . f f f . 
f f f f f c c c c f f f f f 
f f f f b c c c c b f f f f 
f f f c 3 c c c c 3 c f f f 
. f 3 3 c c c c c c 3 3 f . 
. f c c c c 4 4 c c c c f . 
. f f c c 4 4 4 4 c c f f . 
. f f f b f 4 4 f b f f f . 
. f f 4 1 f d d f 1 4 f f . 
. . f f d d d d d d f f . . 
. . e f e 4 4 4 4 e f e . . 
. e 4 f b 3 3 3 3 b f 4 e . 
. 4 d f 3 3 3 3 3 3 c d 4 . 
. 4 4 f 6 6 6 6 6 6 f 4 4 . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`, img`
. . . . . . . . . . . . . . 
. f f f . f f f f . f f f . 
f f f f f c c c c f f f f f 
f f f f b c c c c b f f f f 
f f f c 3 c c c c 3 c f f f 
. f 3 3 c c c c c c 3 3 f . 
. f c c c c 4 4 c c c c f . 
. f f c c 4 4 4 4 c c f f . 
. f f f b f 4 4 f b f f f . 
. f f 4 1 f d d f 1 4 f f . 
. . f f d d d d d 4 e f e . 
. f e f f b b b e d d 4 e . 
. e 4 f b 3 3 3 e d d e . . 
. . . f 6 6 6 6 f e e . . . 
. . . f f f f f f f . . . . 
. . . f f f . . . . . . . . 
`, img`
. . . . . . . . . . . . . . 
. f f f . f f f f . f f f . 
f f f f f c c c c f f f f f 
f f f f b c c c c b f f f f 
f f f c 3 c c c c 3 c f f f 
. f 3 3 c c c c c c 3 3 f . 
. f c c c c 4 4 c c c c f . 
. f f c c 4 4 4 4 c c f f . 
. f f f b f 4 4 f b f f f . 
. f f 4 1 f d d f 1 4 f f . 
. e f e 4 d d d d d f f . . 
. e 4 d d e b b b f f e f . 
. . e d d e 3 3 b e f 4 e . 
. . . e e f 6 6 6 6 f . . . 
. . . . f f f f f f f . . . 
. . . . . . . . f f f . . . 
`];
            case "nena-animation-left":
            case "anim2":return [img`
. . . . f f f f f . f f f . 
. . . f f c c c c f f f f f 
. . f c c c c c c b f f f f 
. . f c c c c c c 3 c f f f 
. f c c c c c c c c 3 3 f . 
. f c c 4 c c c c c f f f . 
. f f e 4 4 c c c f f f f . 
. f f e 4 4 f b f 4 4 f f . 
. . f f d d f 1 4 d 4 f . . 
. . . f d d d d 4 f f f . . 
. . . f e 4 4 4 e e f . . . 
. . . f 3 3 3 e d d 4 . . . 
. . . f 3 3 3 e d d e . . . 
. . . f 6 6 6 f e e f . . . 
. . . . f f f f f f . . . . 
. . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . f f f f f . f f f . 
. . . f f c c c c f f f f f 
. . f c c c c c c b f f f f 
. . f c c c c c c 3 c f f f 
. f c c c c c c c c 3 3 f . 
. f c c 4 c c c c c f f f . 
. f f c 4 4 c c c f f f f . 
. f f f 4 4 f b f 4 4 f f . 
. . f f d d f 1 4 d 4 f . . 
. . . f d d d e e f f f . . 
. . . f e 4 e d d 4 f . . . 
. . . f 3 3 e d d e f . . . 
. . f f 6 6 f e e f f f . . 
. . f f f f f f f f f f . . 
. . . f f f . . . f f . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . f f f f f . f f f . 
. . . f f c c c c f f f f f 
. . f c c c c c c b f f f f 
. . f c c c c c c 3 c f f f 
. f c c c c c c c c 3 3 f . 
. f c c 4 c c c c c f f f . 
. f f c 4 4 c c c f f f f . 
. f f f 4 4 f b f 4 4 f f . 
. . f c d d f 1 4 d 4 f f . 
. . . f d d d d 4 f f f . . 
. . . f e 4 4 4 e d d 4 . . 
. . . f 3 3 3 3 e d d e . . 
. . f f 6 6 6 6 f e e f . . 
. . f f f f f f f f f f . . 
. . . f f f . . . f f . . . 
`];
            case "nena-animation-up":
            case "anim3":return [img`
. f f f . f f f f . f f f . 
f f f f f c c c c f f f f f 
f f f f b c c c c b f f f f 
f f f c 3 c c c c 3 c f f f 
. f 3 3 c c c c c c 3 3 f . 
. f c c c c c c c c c c f . 
. f f c c c c c c c c f f . 
. f f f c c c c c c f f f . 
. f f f f f f f f f f f f . 
. . f f f f f f f f f f . . 
. . e f f f f f f f f e . . 
. e 4 f f f f f f f f 4 e . 
. 4 d f 3 3 3 3 3 3 c d 4 . 
. 4 4 f 6 6 6 6 6 6 f 4 4 . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`, img`
. . . . . . . . . . . . . . 
. f f f . f f f f . f f f . 
f f f f f c c c c f f f f f 
f f f f b c c c c b f f f f 
f f f c 3 c c c c 3 c f f f 
. f 3 3 c c c c c c 3 3 f . 
. f c c c c c c c c c f f . 
. f f c c c c c c c c f f . 
. f f c c c c c c f f f f . 
. f f f f f f f f f f f f . 
. . f f f f f f f f f f . . 
. . e f f f f f f f f e . . 
. . e f f f f f f f f 4 e . 
. . 4 f 3 3 3 3 3 e d d 4 . 
. . e f f f f f f e e 4 . . 
. . . f f f . . . . . . . . 
`, img`
. . . . . . . . . . . . . . 
. f f f . f f f f . f f f . 
f f f f f c c c c f f f f f 
f f f f b c c c c b f f f f 
f f f c 3 c c c c 3 c f f f 
. f 3 3 c c c c c c 3 3 f . 
. f f c c c c c c c c c f . 
. f f c c c c c c c c f f . 
. f f f f c c c c c c f f . 
. f f f f f f f f f f f f . 
. . f f f f f f f f f f . . 
. . e f f f f f f f f e . . 
. e 4 f f f f f f f f e . . 
. 4 d d e 3 3 3 3 3 f 4 . . 
. . 4 e e f f f f f f e . . 
. . . . . . . . f f f . . . 
`];
            case "nena-animation-right":
            case "anim4":return [img`
. . . . . . . . . . . . . . 
. f f f . f f f f f . . . . 
f f f f f c c c c f f . . . 
f f f f b c c c c c c f . . 
f f f c 3 c c c c c c f . . 
. f 3 3 c c c c c c c c f . 
. f f f c c c c c 4 c c f . 
. f f f f c c c 4 4 c f f . 
. f f 4 4 f b f 4 4 f f f . 
. f f 4 d 4 1 f d d c f . . 
. . f f f 4 d d d d f . . . 
. . 4 d d e 4 4 4 e f . . . 
. . e d d e 3 3 3 3 f . . . 
. . f e e f 6 6 6 6 f f . . 
. . f f f f f f f f f f . . 
. . . f f . . . f f f . . . 
`, img`
. . . . . . . . . . . . . . 
. f f f . f f f f f . . . . 
f f f f f c c c c f f . . . 
f f f f b c c c c c c f . . 
f f f c 3 c c c c c c f . . 
. f 3 3 c c c c c c c c f . 
. f f f c c c c c 4 c c f . 
. f f f f c c c 4 4 c f f . 
. f f 4 4 f b f 4 4 f f f . 
. . f 4 d 4 1 f d d f f . . 
. . f f f e e d d d f . . . 
. . . f 4 d d e 4 e f . . . 
. . . f e d d e 3 3 f . . . 
. . f f f e e f 6 6 f f . . 
. . f f f f f f f f f f . . 
. . . f f . . . f f f . . . 
`, img`
. f f f . f f f f f . . . . 
f f f f f c c c c f f . . . 
f f f f b c c c c c c f . . 
f f f c 3 c c c c c c f . . 
. f 3 3 c c c c c c c c f . 
. f f f c c c c c 4 c c f . 
. f f f f c c c 4 4 e f f . 
. f f 4 4 f b f 4 4 e f f . 
. . f 4 d 4 1 f d d f f . . 
. . f f f 4 d d d d f . . . 
. . . f e e 4 4 4 e f . . . 
. . . 4 d d e 3 3 3 f . . . 
. . . e d d e 3 3 3 f . . . 
. . . f e e f 6 6 6 f . . . 
. . . . f f f f f f . . . . 
. . . . . f f f . . . . . . 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Código generado automáticamente. No editar.
